### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by qvalentin** [open-schnick/GitHubActionsTalk#1]
* CD kann Deployment oder auch Delivery heißen (4.4) sieh https://www.redhat.com/en/topics/devops/what-is-ci-cd
* CI: bitte auf die Bedeutung von Integration eingehen (neue Änderung/Commit wird direkt in die bestehende Codebase eingebaut und dann getestet ) (4.3)
* YAML means "YAML Ain't Markup Language" (4.5)
* 5.2 Aufbau ist leer?
* 5.4 - 5.6 "Specifies the events that trigger this workflow." könnte auch besser erklären was passiert (aber du sagst es ja bestimmt)
* 5.7 Bild größer wenns geht
* 5.12 Betriebssytem? Oder sind das eigentlich Docker images wie bei GitLab?
* 6.5 Bilder vllt größer
* 7.2 Deployment sollte man noch aufnehmen und bei Releases näher darauf eingehen wie (erstellen von Docker image oder anderen Packages)

**Comment by open-schnick** [comment]
> * 5.4 - 5.6 "Specifies the events that trigger this workflow." könnte auch besser erklären was passiert (aber du sagst es ja bestimmt)

ist eins zu eins von github docu copy pasted :D

**Comment by open-schnick** [comment]
> > * 5.4 - 5.6 "Specifies the events that trigger this workflow." könnte auch besser erklären was passiert (aber du sagst es ja bestimmt)
> 
> ist eins zu eins von github docu copy pasted :D

Hab ja gesagt die Doku is nicht gut :D

**Comment by open-schnick** [comment]
done :D
